NAME: shop-reviews
LAST DEPLOYED: Sun Jan 28 08:01:35 2024
NAMESPACE: s6bridget
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: shop-reviews/templates/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: espresso-shop-reviews-pdb-v1
spec:
  minAvailable: 2
  selector:
    matchLabels:
      version: v1
---
# Source: shop-reviews/templates/pdb2.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: espresso-shop-reviews-pdb-v2
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: v2
---
# Source: shop-reviews/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: espresso-shop-reviews-v1
  labels:
    app: espresso-shop-reviews
    version: v1
---
# Source: shop-reviews/templates/serviceaccount2.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: espresso-shop-reviews-v2
  labels:
    app: espresso-shop-reviews
    version: v2
---
# Source: shop-reviews/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: espresso-shop-reviews-svc
  labels:
    app: espresso-shop-reviews 
spec:
  type: NodePort
  ports:
    - port: 8092
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: espresso-shop-reviews
    version: v1
    version2: v2
---
# Source: shop-reviews/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espresso-shop-reviews-v1
  labels:
    app: espresso-shop-reviews
    version: v1  
spec:
  selector:
    matchLabels:
      app: espresso-shop-reviews
      version: v1   
  template:
    metadata:
      labels:
        app: espresso-shop-reviews
        version: v1  
    spec:
      serviceAccountName: espresso-shop-reviews-sa-v1 
      securityContext:
        {}
      containers:
        - name: http
          securityContext:
            {}
          image: "achotiab/shop-reviews:v1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
---
# Source: shop-reviews/templates/deployment2 .yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: espresso-shop-reviews-v2
  labels:
    app: espresso-shop-reviews
    version: v2    
spec:
  selector:
    matchLabels:
      app: espresso-shop-reviews
      version: v2    
  template:
    metadata:
      labels:
        app: espresso-shop-reviews
        version: v2  
    spec:
      serviceAccountName: espresso-shop-reviews-sa-v2
      securityContext:
        {}
      containers:
        - name: http
          securityContext:
            {}
          image: "achotiab/shop-reviews:v1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
---
# Source: shop-reviews/templates/hpa.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: espresso-shop-reviews-hpa-v1
  labels:
    app: espresso-shop-reviews
    version: v1  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: espresso-shop-reviews-v1
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
---
# Source: shop-reviews/templates/hpa2.yaml
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: review-hpa2
  labels:
   app: espresso-shop-reviews
   version: v2  
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: espresso-shop-reviews-v2
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

NOTES:
1. Get the application URL by running these commands:
  export NODE_PORT=$(kubectl get --namespace s6bridget -o jsonpath="{.spec.ports[0].nodePort}" services shop-reviews)
  export NODE_IP=$(kubectl get nodes --namespace s6bridget -o jsonpath="{.items[0].status.addresses[0].address}")
  echo http://$NODE_IP:$NODE_PORT
