apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.label.app }}
data:
  POSTGRES_USER: postgres
  POSTGRES_DB: database
  HOSTNAME: postgres-postgresql-ha-postgresql
