apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.appname }}-pdb-v1
spec:
  minAvailable: {{ .Values.minAvailable }}
  selector:
    matchLabels:
      version: {{ .Values.label.version }}