apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appname }}
  labels:
    app: {{ .Values.label.app }}
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # Base64 encoded value of "postgres"
